@ClinicFlow.API_HostAddress = http://localhost:5026

GET {{ClinicFlow.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ClinicFlow.API_HostAddress}}/api/patients
Accept: application/json

###

POST {{ClinicFlow.API_HostAddress}}/api/patients
Content-Type: application/json

{
  "firstName": "Gerardo",
  "lastName": "Panico",
  "birthDate": "2005-01-01T00:00:00",
  "phone": "8888-8888",
  "email": "gerardo@email.com"
}

###

GET {{ClinicFlow.API_HostAddress}}/api/patients/1
Accept: application/json

###

PUT {{ClinicFlow.API_HostAddress}}/api/patients/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Adrian",
  "lastName": "Quiros",
  "birthDate": "2005-01-01T00:00:00",
  "phone": "7777-7777",
  "email": "gerardoactualizado@email.com"
}

###

DELETE {{ClinicFlow.API_HostAddress}}/api/patients/1
Accept: application/json
